### Recuperar todos los países
GET http://localhost:1234/countries

### Crear un nuevo país
POST http://localhost:1234/countries
Content-Type: application/json

{
    "name": "Argentina",
    "iso": "AR"
}

### Eliminar un país
DELETE http://localhost:1234/countries/3
Content-Type: application/json

### Recuperar estados por countryId
GET http://localhost:1234/countries/1/states

### Crear un estado
POST http://localhost:1234/countries/1/states
Content-Type: application/json

{
    "name": "Valle del Cauca"
}

### Eliminar un estado
DELETE http://localhost:1234/states/4
Content-Type: application/json

### Recuperar ciudades de un estado
GET http://localhost:1234/states/1/cities

### Crear una ciudad
POST http://localhost:1234/states/1/cities
Content-Type: application/json

{
    "name": "Fusagasugá"
}

### Eliminar una ciudad
DELETE http://localhost:1234/cities/5

### Obtener las rutas de ua ciudad
GET http://localhost:1234/cities/1/routes

### Crear una nueva ruta
POST http://localhost:1234/cities/1/routes
Content-Type: application/json

{
    "name": "11",
    "description": "Rio Magdalena -> La Esperanza" 
}

### Obtener una ruta por id
GET http://localhost:1234/routes/e66f9621-d93a-4621-bed3-5cf75927bcdc

### Eliminar una ruta
DELETE http://localhost:1234/routes/6b77a104-164f-421f-8dec-1c15ebb8d60c

### Obtener las ejecuciones de una ruta
GET http://localhost:1234/routes/e66f9621-d93a-4621-bed3-5cf75927bcdc/executions

### Crear una nueva ejecución de ruta
POST http://localhost:1234/routes/e66f9621-d93a-4621-bed3-5cf75927bcdc/executions
Content-Type: application/json

{
    "licensePlate": "ABC123",
    "initTime": "2025-07-28 16:23"
}

### Actualizar la ejecución de ruta para ingresar el endTime y los wayPoints
PATCH http://localhost:1234/executions/2?routeId=e66f9621-d93a-4621-bed3-5cf75927bcdc
Content-Type: application/json

{
    "endTime": "2025-07-28 17:02",
    "points": [
        {"lat": 4.635830, "lon": -74.092419, "speed": 10.0},
        {"lat": 4.636092, "lon": -74.092621, "speed": 11.02},
        {"lat": 4.636245, "lon": -74.092747, "speed": 5.01},
        {"lat": 4.636135, "lon": -74.092965, "speed": 5.01},
        {"lat": 4.636001, "lon": -74.093134, "speed": 5.01},
        {"lat": 4.635838, "lon": -74.093047, "speed": 5.01},
        {"lat": 4.635614, "lon": -74.092898, "speed": 5.01}
    ]
}

### Actualizar ejecución de ruta con recorrido parcial Girardot
PATCH http://localhost:1234/executions/2?routeId=e66f9621-d93a-4621-bed3-5cf75927bcdc
Content-Type: application/json

{
    "endTime": "2025-07-28 17:02",
    "points": [
        {"lat":4.3101983,"lon":-74.8079667,"speed":4.8975067138671875},
        {"lat":4.3101983,"lon":-74.8079667,"speed":4.8975067138671875},
        {"lat":4.3101834,"lon":-74.8077915,"speed":4.897542953491211},
        {"lat":4.3101673,"lon":-74.8076178,"speed":4.8977437019348145},
        {"lat":4.3100916,"lon":-74.8075231,"speed":3.791365146636963},
        {"lat":4.3099851,"lon":-74.8075302,"speed":3.7914040088653564},
        {"lat":4.3098436,"lon":-74.8075402,"speed":3.791402578353882},
        {"lat":4.3097097,"lon":-74.8075469,"speed":3.791391372680664},
        {"lat":4.3095735,"lon":-74.8075552,"speed":3.7913975715637207},
        {"lat":4.3095002,"lon":-74.8074583,"speed":5.0262250900268555},
        {"lat":4.3094864,"lon":-74.807319,"speed":5.025989532470703},
        {"lat":4.3094697,"lon":-74.8071388,"speed":5.025970458984375},
        {"lat":4.3094501,"lon":-74.8069324,"speed":5.026230335235596}
    ]
}

### Eliminar una ejecución de ruta
DELETE http://localhost:1234/executions/5